name: nwb_to_RasterVis
channels:
- conda-forge
- edeno
- franklab
dependencies:
- loren_frank_data_processing
- pynwb
- jupyter
- jupyterlab
- matplotlib
- numpy
- pip
- pip:
  - dandi
  - remfile
  - kachery-cloud